import type { MediaItem } from './types'

export const seedItems: MediaItem[] = [
  {
    id: 'arrival',
    canonicalTitle: 'Arrival',
    category: 'movie',
    moods: ['thoughtful', 'sci-fi', 'quiet'],
    themes: ['aliens', 'language', 'memory'],
    reason: 'Smart, emotional sci-fi that rewards actually paying attention.',
    status: 'shortlist',
    priority: 4,
    needsReview: false,
    sourceArtifacts: [],
    createdAt: '2026-04-01T00:00:00.000Z',
    updatedAt: '2026-04-01T00:00:00.000Z',
  },
  {
    id: 'severance',
    canonicalTitle: 'Severance',
    category: 'tv',
    moods: ['weird', 'mystery', 'prestige'],
    themes: ['work', 'identity', 'conspiracy'],
    reason: 'For when you want a puzzle box instead of another doomscroll box.',
    status: 'curious',
    priority: 3,
    needsReview: false,
    sourceArtifacts: [],
    createdAt: '2026-04-02T00:00:00.000Z',
    updatedAt: '2026-04-02T00:00:00.000Z',
  },
  {
    id: 'project-hail-mary',
    canonicalTitle: 'Project Hail Mary',
    category: 'book',
    moods: ['fun', 'science', 'page-turner'],
    themes: ['space', 'competence', 'friendship'],
    reason: 'Competence porn in space. Very legal, very cool.',
    status: 'curious',
    priority: 3,
    needsReview: false,
    sourceArtifacts: [],
    createdAt: '2026-04-03T00:00:00.000Z',
    updatedAt: '2026-04-03T00:00:00.000Z',
  },
  {
    id: 'outer-wilds',
    canonicalTitle: 'Outer Wilds',
    category: 'game',
    moods: ['exploration', 'mystery', 'wonder'],
    themes: ['space', 'time loop', 'discovery'],
    reason: 'Best if you know almost nothing and let curiosity drive.',
    status: 'shortlist',
    priority: 5,
    needsReview: false,
    sourceArtifacts: [],
    createdAt: '2026-04-04T00:00:00.000Z',
    updatedAt: '2026-04-04T00:00:00.000Z',
  },
  {
    id: 'dune-inbox',
    canonicalTitle: 'Dune',
    category: 'other',
    moods: ['epic', 'sci-fi'],
    themes: ['ambiguous capture'],
    reason: 'Captured from a future agent flow; needs review before the compass can pick it.',
    status: 'inbox',
    priority: 3,
    needsReview: true,
    agentConfidence: 0.61,
    confidenceReasons: ['Title is clear, but category/version is ambiguous.'],
    sourceArtifacts: [
      {
        id: 'artifact-dune-text',
        type: 'text',
        contentText: 'Dune',
        createdAt: '2026-04-05T00:00:00.000Z',
      },
    ],
    createdAt: '2026-04-05T00:00:00.000Z',
    updatedAt: '2026-04-05T00:00:00.000Z',
  },
]
